version: "3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
  web:
    build: .
    environment:
      - PORT=4001
      - DATABASE_HOST=db
    command: npm start
    volumes:
      - .:/app
    ports:
      - 4001:4001
    links:
      - db
    depends_on:
      - db
